### ISSUE TITLE
HTML special characters in Slack display as entities in Discord

### ISSUE THREAD

**Issue by adambirtles** [LukeMoll/slack-discord-bridge#1]
When a message is sent from Slack, the HTML special characters `<`, `>`, and `&` show up in Discord as HTML entities `&lt;`, `&gt;`, and `&amp;`.

Here are a pair of screenshots demonstrating the issue:

![Characters on Slack](https://user-images.githubusercontent.com/4145728/35537006-948ed172-0540-11e8-9178-dffd648bfbe1.png) ![Entities on Discord](https://user-images.githubusercontent.com/4145728/35537019-a2130a02-0540-11e8-944e-a9693abf2192.png)

**Comment by LukeMoll** [comment]
Fixed in [`4d0b04`](https://github.com/HackSoc/slack-discord-bridge/commit/4d0b04f91d23fa3d71e90926574073846c5225dd).
