### ISSUE TITLE
@slack/client dependency

### ISSUE THREAD

**Issue by qaisjp** [LukeMoll/slack-discord-bridge#2]
There is a dependency on [@slack/client](https://www.npmjs.com/package/@slack/client) missing in the package.json

**Comment by LukeMoll** [comment]
So there is - I'll add it later tonight. Thanks for spotting it!

**Comment by LukeMoll** [comment]
Fixed with [1acf30](https://github.com/HackSoc/slack-discord-bridge/commit/1acf30a11782efc7edd0fdf57f2c7f5cd09f3933)
