### ISSUE TITLE
Discord attachments don't send to Slack

### ISSUE THREAD

**Issue by qaisjp** [LukeMoll/slack-discord-bridge#5]
Discord media should send a link to Slack.

[Here's reference implementation in discord-irc](https://github.com/reactiflux/discord-irc/blob/master/lib/bot.js#L352-L360).

**Comment by LukeMoll** [comment]
It's on the (non-public) roadmap. Similarly, Slack media should be forwarded.

**Comment by qaisjp** [comment]
Slack media is currently forwarded (but inaccessible for those without access to the organisation, and this is unavoidable as far as I know without some sort of proxy server).

May I work on a PR for this?

**Comment by LukeMoll** [comment]
Sure! Even with access to the organisation links to Slack don't tend to work, so I'd put that feature down as incomplete.
